# ONLINE_SALE 테이블과 OFFLINE_SALE 테이블에서 
#  3월의 오프라인 / 온라인
# 판매 날짜, 상품 ID, 유저 ID, 판매량을 출력하는 SQL 
# OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 로 표시하기 
#  결과는 판매일 오름차순, 상품 ID 오름차순, 유저 ID 오름차순 
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE as A 
WHERE SALES_DATE LIKE '2022-03%'
UNION
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE as B
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID